/**
 * Canonical permission constants — verbatim from the frozen
 * AI_CONTENT_ROLE_PERMISSION_MATRIX_V1.0.md §Permission Categories.
 * No permission introduced here that isn't already in that document.
 */
export const PERMISSIONS = {
  WORKSPACE_VIEW: "WORKSPACE_VIEW",
  WORKSPACE_CREATE: "WORKSPACE_CREATE",
  WORKSPACE_UPDATE: "WORKSPACE_UPDATE",
  WORKSPACE_DELETE: "WORKSPACE_DELETE",

  PROJECT_VIEW: "PROJECT_VIEW",
  PROJECT_CREATE: "PROJECT_CREATE",
  PROJECT_UPDATE: "PROJECT_UPDATE",
  PROJECT_DELETE: "PROJECT_DELETE",

  KP_VIEW: "KP_VIEW",
  KP_CREATE: "KP_CREATE",
  KP_UPDATE: "KP_UPDATE",
  KP_DELETE: "KP_DELETE",

  RESEARCH_RUN: "RESEARCH_RUN",
  RESEARCH_APPROVE: "RESEARCH_APPROVE",

  BLOG_CREATE: "BLOG_CREATE",
  BLOG_EDIT: "BLOG_EDIT",
  BLOG_REVIEW: "BLOG_REVIEW",
  BLOG_APPROVE: "BLOG_APPROVE",
  BLOG_PUBLISH: "BLOG_PUBLISH",

  VIDEO_CREATE: "VIDEO_CREATE",
  VIDEO_RENDER: "VIDEO_RENDER",
  VIDEO_EDIT: "VIDEO_EDIT",
  VIDEO_APPROVE: "VIDEO_APPROVE",
  VIDEO_PUBLISH: "VIDEO_PUBLISH",

  SEO_EDIT: "SEO_EDIT",
  SEO_SCORE: "SEO_SCORE",
  SEO_APPROVE: "SEO_APPROVE",

  PUBLISH_CREATE: "PUBLISH_CREATE",
  PUBLISH_EXECUTE: "PUBLISH_EXECUTE",
  PUBLISH_CANCEL: "PUBLISH_CANCEL",

  ANALYTICS_VIEW: "ANALYTICS_VIEW",
  ANALYTICS_EXPORT: "ANALYTICS_EXPORT",

  USER_MANAGE: "USER_MANAGE",
  ROLE_MANAGE: "ROLE_MANAGE",
  SETTINGS_MANAGE: "SETTINGS_MANAGE",
  AUDIT_VIEW: "AUDIT_VIEW",
} as const;

export type PermissionConstant = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_CATEGORIES: Record<string, PermissionConstant[]> = {
  Workspace: [PERMISSIONS.WORKSPACE_VIEW, PERMISSIONS.WORKSPACE_CREATE, PERMISSIONS.WORKSPACE_UPDATE, PERMISSIONS.WORKSPACE_DELETE],
  Projects: [PERMISSIONS.PROJECT_VIEW, PERMISSIONS.PROJECT_CREATE, PERMISSIONS.PROJECT_UPDATE, PERMISSIONS.PROJECT_DELETE],
  "Knowledge Packs": [PERMISSIONS.KP_VIEW, PERMISSIONS.KP_CREATE, PERMISSIONS.KP_UPDATE, PERMISSIONS.KP_DELETE],
  Research: [PERMISSIONS.RESEARCH_RUN, PERMISSIONS.RESEARCH_APPROVE],
  Blog: [PERMISSIONS.BLOG_CREATE, PERMISSIONS.BLOG_EDIT, PERMISSIONS.BLOG_REVIEW, PERMISSIONS.BLOG_APPROVE, PERMISSIONS.BLOG_PUBLISH],
  Video: [PERMISSIONS.VIDEO_CREATE, PERMISSIONS.VIDEO_RENDER, PERMISSIONS.VIDEO_EDIT, PERMISSIONS.VIDEO_APPROVE, PERMISSIONS.VIDEO_PUBLISH],
  SEO: [PERMISSIONS.SEO_EDIT, PERMISSIONS.SEO_SCORE, PERMISSIONS.SEO_APPROVE],
  Publishing: [PERMISSIONS.PUBLISH_CREATE, PERMISSIONS.PUBLISH_EXECUTE, PERMISSIONS.PUBLISH_CANCEL],
  Analytics: [PERMISSIONS.ANALYTICS_VIEW, PERMISSIONS.ANALYTICS_EXPORT],
  Administration: [PERMISSIONS.USER_MANAGE, PERMISSIONS.ROLE_MANAGE, PERMISSIONS.SETTINGS_MANAGE, PERMISSIONS.AUDIT_VIEW],
};

/**
 * The 8 roles, verbatim from the Role & Permission Matrix. This is the
 * first concrete resolution of the granular role -> permission mapping
 * flagged as an open gap in the Phase-0 Readiness Report — derived
 * directly from each role's documented responsibilities in that doc, not
 * invented here.
 */
export const ROLE_PERMISSIONS: Record<string, PermissionConstant[]> = {
  Owner: Object.values(PERMISSIONS),
  Administrator: [
    PERMISSIONS.WORKSPACE_VIEW,
    PERMISSIONS.WORKSPACE_UPDATE,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE,
    PERMISSIONS.KP_VIEW,
    PERMISSIONS.KP_CREATE,
    PERMISSIONS.KP_UPDATE,
    PERMISSIONS.KP_DELETE,
    PERMISSIONS.RESEARCH_RUN,
    PERMISSIONS.RESEARCH_APPROVE,
    PERMISSIONS.BLOG_CREATE,
    PERMISSIONS.BLOG_EDIT,
    PERMISSIONS.BLOG_REVIEW,
    PERMISSIONS.BLOG_APPROVE,
    PERMISSIONS.BLOG_PUBLISH,
    PERMISSIONS.VIDEO_CREATE,
    PERMISSIONS.VIDEO_RENDER,
    PERMISSIONS.VIDEO_EDIT,
    PERMISSIONS.VIDEO_APPROVE,
    PERMISSIONS.VIDEO_PUBLISH,
    PERMISSIONS.SEO_EDIT,
    PERMISSIONS.SEO_SCORE,
    PERMISSIONS.SEO_APPROVE,
    PERMISSIONS.PUBLISH_CREATE,
    PERMISSIONS.PUBLISH_EXECUTE,
    PERMISSIONS.PUBLISH_CANCEL,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ANALYTICS_EXPORT,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    // Deliberately excluded: WORKSPACE_CREATE/DELETE, ROLE_MANAGE,
    // SETTINGS_MANAGE — Owner-exclusive per FR-WS-001 and the Matrix's
    // "Cannot: Transfer Ownership" note.
  ],
  "Content Manager": [
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.KP_VIEW,
    PERMISSIONS.RESEARCH_RUN,
    PERMISSIONS.BLOG_CREATE,
    PERMISSIONS.BLOG_EDIT,
    PERMISSIONS.BLOG_REVIEW,
    PERMISSIONS.BLOG_APPROVE,
    PERMISSIONS.VIDEO_CREATE,
    PERMISSIONS.VIDEO_EDIT,
    PERMISSIONS.VIDEO_APPROVE,
    PERMISSIONS.PUBLISH_CREATE,
    PERMISSIONS.ANALYTICS_VIEW,
  ],
  "Content Writer": [PERMISSIONS.RESEARCH_RUN, PERMISSIONS.BLOG_CREATE, PERMISSIONS.BLOG_EDIT, PERMISSIONS.KP_VIEW],
  "SEO Specialist": [
    PERMISSIONS.RESEARCH_RUN,
    PERMISSIONS.SEO_EDIT,
    PERMISSIONS.SEO_SCORE,
    PERMISSIONS.SEO_APPROVE,
    PERMISSIONS.BLOG_EDIT,
    PERMISSIONS.ANALYTICS_VIEW,
  ],
  "Video Editor": [PERMISSIONS.VIDEO_CREATE, PERMISSIONS.VIDEO_RENDER, PERMISSIONS.VIDEO_EDIT],
  Publisher: [
    PERMISSIONS.PUBLISH_CREATE,
    PERMISSIONS.PUBLISH_EXECUTE,
    PERMISSIONS.PUBLISH_CANCEL,
    PERMISSIONS.BLOG_PUBLISH,
    PERMISSIONS.VIDEO_PUBLISH,
  ],
  Analyst: [PERMISSIONS.ANALYTICS_VIEW, PERMISSIONS.ANALYTICS_EXPORT],
};
