import { randomUUID } from "crypto";
import { Injectable, UnprocessableEntityException } from "@nestjs/common";
import { Prisma } from "../../../generated/prisma";
import { PrismaService } from "../../prisma/prisma.service";
import { AuditService } from "../audit/audit.service";
import { KnowledgePacksService } from "../knowledge-packs/knowledge-packs.service";
import { ContentItemsService, type ContentActor } from "../content/content-items.service";
import { CreateVideoDto } from "./dto/create-video.dto";
import type { VideoApproveDto, VideoRejectDto, VideoSubmitForReviewDto } from "./dto/video-review.dto";
import { VIDEO_ERRORS } from "./video.errors";
import { emptyPipelineState, readPipelineState, writePipelineState } from "./video-pipeline-state";
import { VideoPipelineService } from "./video-pipeline.service";

export interface VideoActor {
  userPublicId: string;
  userInternalId: string;
}

interface RequestContext {
  ipAddress?: string;
  correlationId: string;
}

const NEW_VIDEO_PLACEHOLDER_BODY = { script: "(script pending — generated by the video pipeline)" };

/**
 * Module 7 Phase 7.1 — Video module facade. Structural mirror of Module
 * 6's `BlogService`.
 *
 * `create` composes existing modules only:
 *  - Module 2: exact-version, ADR-004 non-substitution Knowledge Pack
 *    gate (never "the workspace's active pack").
 *  - Module 1E: `ContentItemsService.create` (VIDEO) + `start`
 *    (DRAFT → IN_PROGRESS). Permission (VIDEO_CREATE / VIDEO_EDIT) is
 *    enforced inside those calls via ContentPermissionResolver.
 *  - This phase adds: the 1:1 `video_scripts` row (target_platform set,
 *    everything else deferred) and the `content_items.metadata.videoPipeline`
 *    bag.
 *
 * No AI generation happens in Phase 7.1 — `create` ends with the item in
 * IN_PROGRESS and every pipeline stage PENDING.
 */
@Injectable()
export class VideoService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly audit: AuditService,
    private readonly knowledgePacks: KnowledgePacksService,
    private readonly contentItems: ContentItemsService,
    private readonly pipeline: VideoPipelineService,
  ) {}

  private contentActor(actor: VideoActor): ContentActor {
    return { publicId: actor.userPublicId, internalId: actor.userInternalId };
  }

  async create(workspaceId: string, actor: VideoActor, dto: CreateVideoDto, ctx: RequestContext): Promise<Record<string, unknown>> {
    if (!dto.topic.trim()) {
      throw new UnprocessableEntityException({ code: VIDEO_ERRORS.VIDEO_TOPIC_REQUIRED, message: "A non-empty topic is required." });
    }

    // Exact-version, ADR-004 non-substitution — never "the workspace's active pack".
    const pack = await this.knowledgePacks.findOne(workspaceId, dto.knowledgePackVersionId);
    if (pack.status !== "ACTIVE") {
      throw new UnprocessableEntityException({
        code: VIDEO_ERRORS.VIDEO_KNOWLEDGE_PACK_NOT_ACTIVE,
        message: `Knowledge Pack is "${pack.status}", not ACTIVE — a video pipeline cannot run against it.`,
      });
    }

    const workspace = { id: workspaceId };
    const contentActor = this.contentActor(actor);

    // Module 1E owns item + version-1 creation. contentType VIDEO is one
    // of the two families Module 1E's ContentPermissionResolver supports
    // (BLOG / VIDEO) — SHORT/REEL remain reserved for a later module that
    // adds their own permission families.
    const item = await this.contentItems.create(
      workspace,
      contentActor,
      { contentType: "VIDEO", title: dto.topic.trim(), projectId: dto.projectId, body: NEW_VIDEO_PLACEHOLDER_BODY },
      { ipAddress: ctx.ipAddress },
    );

    if (dto.seriesId) {
      await this.contentItems.assignSeries(workspace, contentActor, item.publicId, { seriesId: dto.seriesId }, { ipAddress: ctx.ipAddress });
    }

    await this.contentItems.start(workspace, contentActor, item.publicId, { ipAddress: ctx.ipAddress });

    // Create the 1:1 video_scripts row + initialize the pipeline state
    // bag under a single row lock on the content item, so a concurrent
    // request can never write a second script row or a half-formed bag.
    const row = await this.prisma.contentItem.findFirstOrThrow({ where: { publicId: item.publicId }, select: { id: true } });
    await this.prisma.$transaction(async (tx) => {
      await tx.$queryRaw`SELECT id FROM content_items WHERE id = ${row.id}::uuid FOR UPDATE`;

      const script = await tx.videoScript.create({
        data: {
          id: randomUUID(),
          publicId: randomUUID(),
          workspaceId,
          contentItemId: row.id,
          targetPlatform: dto.targetPlatform,
          durationSecondsTarget: dto.durationSecondsTarget ?? null,
          createdById: actor.userInternalId,
        },
        select: { publicId: true },
      });

      const current = await tx.contentItem.findFirstOrThrow({ where: { id: row.id }, select: { metadata: true } });
      const state = emptyPipelineState(dto.knowledgePackVersionId, script.publicId);
      await tx.contentItem.update({
        where: { id: row.id },
        data: { metadata: writePipelineState(current.metadata, state) as Prisma.InputJsonValue },
      });

      await this.audit.recordWithinTransaction(tx, {
        action: "CONTENT_ITEM_UPDATED",
        actorUserId: actor.userInternalId,
        workspaceId,
        entityType: "content_item",
        entityId: item.publicId,
        afterState: {
          "videoPipeline.created": true,
          knowledgePackVersionId: dto.knowledgePackVersionId,
          videoScriptPublicId: script.publicId,
          targetPlatform: dto.targetPlatform,
        },
        ipAddress: ctx.ipAddress,
      });
    });

    return this.pipeline.projectReadModel(workspaceId, item.publicId);
  }

  async list(workspaceId: string, actor: VideoActor): Promise<Record<string, unknown>[]> {
    // Reuse Module 1E's type-aware list (VIDEO_VIEW enforced inside), then
    // keep only pipeline items and reduce each to a compact summary.
    const items = await this.contentItems.list({ id: workspaceId }, this.contentActor(actor), { contentType: "VIDEO" });
    const pipelineItems = items.filter((i) => readPipelineState(i.metadata) !== null);

    const scripts = await this.prisma.videoScript.findMany({
      where: { workspaceId, deletedAt: null, contentItem: { publicId: { in: pipelineItems.map((i) => i.publicId) } } },
      select: { targetPlatform: true, contentItem: { select: { publicId: true } } },
    });
    const platformByPublicId = new Map(scripts.map((s) => [s.contentItem.publicId, s.targetPlatform]));

    return pipelineItems
      .map((i) => {
        const state = readPipelineState(i.metadata)!;
        return {
          publicId: i.publicId,
          title: i.title,
          status: i.status,
          knowledgePackVersionId: state.knowledgePackVersionId,
          targetPlatform: platformByPublicId.get(i.publicId) ?? null,
          brief: state.brief.status,
          script: state.script.status,
          scenePlan: state.scenePlan.status,
          render: state.render.status,
          seo: state.seo.status,
        };
      });
  }

  // ---------------------------------------------------------------------
  // Human-review handoff — delegates to Module 1E, never re-implements it
  // (mirrors BlogService.submitForReview/approve/reject exactly).
  // ---------------------------------------------------------------------

  async submitForReview(workspaceId: string, actor: VideoActor, itemPublicId: string, dto: VideoSubmitForReviewDto, ctx: RequestContext): Promise<Record<string, unknown>> {
    await this.pipeline.assertReadyForReview(workspaceId, itemPublicId, actor, ctx);
    // viaVideoPipeline: true — the internal-only flag Phase 7.1 added to
    // ContentItemsService.submitForReview. Not part of any DTO; a caller
    // can never supply it over HTTP. The generic route stays sealed with
    // CONTENT_ITEM_VIDEO_REVIEW_VIA_PIPELINE.
    await this.contentItems.submitForReview({ id: workspaceId }, this.contentActor(actor), itemPublicId, dto, { ipAddress: ctx.ipAddress }, { viaVideoPipeline: true });
    return this.pipeline.projectReadModel(workspaceId, itemPublicId);
  }

  async approve(workspaceId: string, actor: VideoActor, itemPublicId: string, dto: VideoApproveDto, ctx: RequestContext): Promise<Record<string, unknown>> {
    await this.contentItems.approve({ id: workspaceId }, this.contentActor(actor), itemPublicId, dto, { ipAddress: ctx.ipAddress });
    return this.pipeline.projectReadModel(workspaceId, itemPublicId);
  }

  async reject(workspaceId: string, actor: VideoActor, itemPublicId: string, dto: VideoRejectDto, ctx: RequestContext): Promise<Record<string, unknown>> {
    await this.contentItems.reject({ id: workspaceId }, this.contentActor(actor), itemPublicId, dto, { ipAddress: ctx.ipAddress });
    return this.pipeline.projectReadModel(workspaceId, itemPublicId);
  }
}
