-- Module 7 Phase 7.5 — Video Rendering + QA.
-- Purely additive: one new enum (VideoRenderJobStatus) and one new table
-- (video_render_jobs). No ALTER to any existing table's columns, no data
-- backfill, no destructive change. video_render_jobs is the render
-- analogue of media_jobs / ai_jobs (AI_CONTENT_DATABASE_AND_ENTITY_
-- DESIGN_V1.0.md §5 extension-table pattern), linked 1:1 to a generic
-- background_jobs dispatch row. The rendered binary is never stored in
-- Postgres — it lands in object storage as a VIDEO MediaAsset; this table
-- records only its identity + inspected metadata (checkpoint §2/§13).
--
-- The Prisma diff engine again proposes dropping the hand-written
-- DEFERRABLE constraints "projects_slug_reservation_fkey" /
-- "workspaces_slug_reservation_fkey" (see the Phase 2.1 / 5.1 / 6.1 /
-- 6.2 / 7.1 / 7.4 migrations' own notes). Deliberately NOT applied —
-- this migration was generated by a datamodel-to-datamodel diff and
-- touches neither constraint.

-- CreateEnum
CREATE TYPE "VideoRenderJobStatus" AS ENUM ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'TIMED_OUT');

-- CreateTable
CREATE TABLE "video_render_jobs" (
    "id" UUID NOT NULL,
    "public_id" UUID NOT NULL,
    "workspace_id" UUID NOT NULL,
    "content_item_id" UUID NOT NULL,
    "background_job_id" UUID,
    "status" "VideoRenderJobStatus" NOT NULL DEFAULT 'QUEUED',
    "target_platform" TEXT NOT NULL,
    "export_profile_id" TEXT NOT NULL,
    "render_input_snapshot" JSONB NOT NULL,
    "render_input_version" INTEGER NOT NULL DEFAULT 1,
    "script_version_hash" TEXT NOT NULL,
    "scene_asset_fingerprint" TEXT NOT NULL,
    "voice_audio_asset_public_id" UUID NOT NULL,
    "subtitle_vtt_asset_public_id" UUID,
    "output_media_asset_public_id" UUID,
    "output_media_asset_group_id" UUID,
    "output_width" INTEGER,
    "output_height" INTEGER,
    "output_duration_ms" INTEGER,
    "output_fps" INTEGER,
    "output_byte_size" BIGINT,
    "output_checksum_sha256" TEXT,
    "output_container" TEXT,
    "output_video_codec" TEXT,
    "output_audio_codec" TEXT,
    "render_engine" TEXT,
    "render_engine_version" TEXT,
    "attempt" INTEGER NOT NULL DEFAULT 0,
    "error_code" TEXT,
    "error_message_safe" TEXT,
    "correlation_id" TEXT NOT NULL,
    "started_at" TIMESTAMP(3),
    "completed_at" TIMESTAMP(3),
    "created_by" UUID,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),

    CONSTRAINT "video_render_jobs_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "video_render_jobs_public_id_key" ON "video_render_jobs"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "video_render_jobs_background_job_id_key" ON "video_render_jobs"("background_job_id");

-- CreateIndex
CREATE INDEX "video_render_jobs_workspace_id_idx" ON "video_render_jobs"("workspace_id");

-- CreateIndex
CREATE INDEX "video_render_jobs_status_idx" ON "video_render_jobs"("status");

-- CreateIndex
CREATE INDEX "video_render_jobs_correlation_id_idx" ON "video_render_jobs"("correlation_id");

-- CreateIndex
CREATE INDEX "video_render_jobs_content_item_id_idx" ON "video_render_jobs"("content_item_id");

-- AddForeignKey
ALTER TABLE "video_render_jobs" ADD CONSTRAINT "video_render_jobs_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "video_render_jobs" ADD CONSTRAINT "video_render_jobs_content_item_id_workspace_id_fkey" FOREIGN KEY ("content_item_id", "workspace_id") REFERENCES "content_items"("id", "workspace_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "video_render_jobs" ADD CONSTRAINT "video_render_jobs_background_job_id_fkey" FOREIGN KEY ("background_job_id") REFERENCES "background_jobs"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "video_render_jobs" ADD CONSTRAINT "video_render_jobs_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

