import { Injectable, UnprocessableEntityException } from "@nestjs/common";
import { PrismaService } from "../../prisma/prisma.service";
import { AuditService } from "../audit/audit.service";
import { KnowledgePacksService } from "../knowledge-packs/knowledge-packs.service";
import { ContentItemsService, type ContentActor } from "../content/content-items.service";
import { CreateBlogDto } from "./dto/create-blog.dto";
import type { BlogSubmitForReviewDto, BlogApproveDto, BlogRejectDto } from "./dto/blog-review.dto";
import { BLOG_ERRORS } from "./blog.errors";
import { emptyPipelineState, readPipelineState, writePipelineState } from "./blog-pipeline-state";
import { BlogPipelineService, type BlogActor } from "./blog-pipeline.service";

interface RequestContext {
  ipAddress?: string;
  correlationId: string;
}

const NEW_BLOG_PLACEHOLDER_BODY = { content: "(draft pending — generated by the blog pipeline)" };

/**
 * Module 6 Phase 6.3 — Blog module facade.
 *
 * `create` composes Module 2 (exact-version Knowledge Pack gate), Module
 * 1E (`ContentItemsService.create` + `start`), and initializes the
 * pipeline state before kicking off the brief agent. Review handoff
 * (`submitForReview` / `approve` / `reject`) delegates STRAIGHT to
 * `ContentItemsService` — the Blog module never re-implements approval
 * logic; it only enforces the Blog-specific Quality Gates before
 * submit-for-review (below-threshold score can never bypass the human
 * review gate).
 */
@Injectable()
export class BlogService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly audit: AuditService,
    private readonly knowledgePacks: KnowledgePacksService,
    private readonly contentItems: ContentItemsService,
    private readonly pipeline: BlogPipelineService,
  ) {}

  private contentActor(actor: BlogActor): ContentActor {
    return { publicId: actor.userPublicId, internalId: actor.userInternalId };
  }

  async create(workspaceId: string, actor: BlogActor, dto: CreateBlogDto, ctx: RequestContext): Promise<Record<string, unknown>> {
    if (!dto.topic.trim()) {
      throw new UnprocessableEntityException({ code: BLOG_ERRORS.BLOG_TOPIC_REQUIRED, message: "A non-empty topic is required." });
    }

    // Exact-version, ADR-004 non-substitution — never "the workspace's active pack".
    const pack = await this.knowledgePacks.findOne(workspaceId, dto.knowledgePackVersionId);
    if (pack.status !== "ACTIVE") {
      throw new UnprocessableEntityException({
        code: BLOG_ERRORS.BLOG_KNOWLEDGE_PACK_NOT_ACTIVE,
        message: `Knowledge Pack is "${pack.status}", not ACTIVE — a blog pipeline cannot run against it.`,
      });
    }

    const workspace = { id: workspaceId };
    const contentActor = this.contentActor(actor);

    // Module 1E owns item + version-1 creation and the DRAFT→IN_PROGRESS
    // transition; permission (BLOG_CREATE / BLOG_EDIT) is enforced inside
    // those calls via ContentPermissionResolver.
    const item = await this.contentItems.create(
      workspace,
      contentActor,
      { contentType: "BLOG", title: dto.topic.trim(), projectId: dto.projectId, body: NEW_BLOG_PLACEHOLDER_BODY },
      { ipAddress: ctx.ipAddress },
    );

    if (dto.seriesId) {
      await this.contentItems.assignSeries(workspace, contentActor, item.publicId, { seriesId: dto.seriesId }, { ipAddress: ctx.ipAddress });
    }

    await this.contentItems.start(workspace, contentActor, item.publicId, { ipAddress: ctx.ipAddress });

    // Initialize the pipeline state bag under a row lock, then submit the
    // brief agent (its own durable ai.execute.v1 job — no sync AI here).
    const row = await this.prisma.contentItem.findFirstOrThrow({ where: { publicId: item.publicId }, select: { id: true, metadata: true } });
    await this.prisma.contentItem.update({
      where: { id: row.id },
      data: { metadata: writePipelineState(row.metadata, emptyPipelineState(dto.knowledgePackVersionId)) as never },
    });
    await this.audit.record({
      action: "CONTENT_ITEM_UPDATED",
      actorUserId: actor.userInternalId,
      workspaceId,
      entityType: "content_item",
      entityId: item.publicId,
      afterState: { "blogPipeline.created": true, knowledgePackVersionId: dto.knowledgePackVersionId },
      correlationId: ctx.correlationId,
    });

    await this.pipeline.generateBrief(workspaceId, actor, item.publicId, ctx);

    return this.pipeline.projectReadModel(workspaceId, item.publicId);
  }

  async list(workspaceId: string, actor: BlogActor): Promise<Record<string, unknown>[]> {
    // Reuse Module 1E's type-aware list (BLOG_VIEW enforced inside), then
    // keep only pipeline items and reduce each to a compact summary.
    const items = await this.contentItems.list({ id: workspaceId }, this.contentActor(actor), { contentType: "BLOG" });
    return items
      .filter((i) => readPipelineState(i.metadata) !== null)
      .map((i) => {
        const state = readPipelineState(i.metadata)!;
        return {
          publicId: i.publicId,
          title: i.title,
          status: i.status,
          knowledgePackVersionId: state.knowledgePackVersionId,
          brief: state.brief.status,
          outline: state.outline.status,
          draft: state.draft.status,
          seo: state.seo.status,
          qa: state.qa.status,
          scoring: { status: state.scoring.status, passed: state.scoring.passed, overallScore: state.scoring.overallScore },
        };
      });
  }

  async submitForReview(workspaceId: string, actor: BlogActor, itemPublicId: string, dto: BlogSubmitForReviewDto, ctx: RequestContext): Promise<Record<string, unknown>> {
    await this.pipeline.assertReadyForReview(workspaceId, itemPublicId, actor, ctx);
    await this.contentItems.submitForReview({ id: workspaceId }, this.contentActor(actor), itemPublicId, dto, { ipAddress: ctx.ipAddress }, { viaBlogPipeline: true });
    return this.pipeline.projectReadModel(workspaceId, itemPublicId);
  }

  async approve(workspaceId: string, actor: BlogActor, itemPublicId: string, dto: BlogApproveDto, ctx: RequestContext): Promise<Record<string, unknown>> {
    await this.contentItems.approve({ id: workspaceId }, this.contentActor(actor), itemPublicId, dto, { ipAddress: ctx.ipAddress });
    return this.pipeline.projectReadModel(workspaceId, itemPublicId);
  }

  async reject(workspaceId: string, actor: BlogActor, itemPublicId: string, dto: BlogRejectDto, ctx: RequestContext): Promise<Record<string, unknown>> {
    await this.contentItems.reject({ id: workspaceId }, this.contentActor(actor), itemPublicId, dto, { ipAddress: ctx.ipAddress });
    return this.pipeline.projectReadModel(workspaceId, itemPublicId);
  }
}
